USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'pgv_admin')
    CREATE LOGIN pgv_admin WITH PASSWORD = '123456', DEFAULT_DATABASE = QLDSV_HTC, CHECK_POLICY = OFF;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'khoa_cntt')
    CREATE LOGIN khoa_cntt WITH PASSWORD = 'khoa123', DEFAULT_DATABASE = QLDSV_HTC, CHECK_POLICY = OFF;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'khoa_vt')
    CREATE LOGIN khoa_vt WITH PASSWORD = 'khoa456', DEFAULT_DATABASE = QLDSV_HTC, CHECK_POLICY = OFF;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'sv')
    CREATE LOGIN sv WITH PASSWORD = 'sv123', DEFAULT_DATABASE = QLDSV_HTC, CHECK_POLICY = OFF;
GO

GRANT ALTER ANY LOGIN TO [pgv_admin];
GO

USE QLDSV_HTC;
GO

IF ISNULL(IS_ROLEMEMBER(N'KHOA', N'khoa_chung'), 0) = 1
    ALTER ROLE KHOA DROP MEMBER khoa_chung;
GO

IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'khoa_chung')
    DROP USER khoa_chung;
GO

USE master;
GO

IF EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'khoa_chung')
    DROP LOGIN khoa_chung;
GO

USE QLDSV_HTC;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'pgv_admin')
    CREATE USER pgv_admin FOR LOGIN pgv_admin;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'khoa_cntt')
    CREATE USER khoa_cntt FOR LOGIN khoa_cntt;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'khoa_vt')
    CREATE USER khoa_vt FOR LOGIN khoa_vt;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'sv')
    CREATE USER sv FOR LOGIN sv;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'PGV' AND type = 'R')
    CREATE ROLE PGV;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'KHOA' AND type = 'R')
    CREATE ROLE KHOA;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'NHOM_SV' AND type = 'R')
    CREATE ROLE NHOM_SV;
GO

IF ISNULL(IS_ROLEMEMBER(N'PGV', N'pgv_admin'), 0) = 0
    ALTER ROLE PGV ADD MEMBER pgv_admin;
GO

IF ISNULL(IS_ROLEMEMBER(N'KHOA', N'khoa_cntt'), 0) = 0
    ALTER ROLE KHOA ADD MEMBER khoa_cntt;
GO

IF ISNULL(IS_ROLEMEMBER(N'KHOA', N'khoa_vt'), 0) = 0
    ALTER ROLE KHOA ADD MEMBER khoa_vt;
GO

IF ISNULL(IS_ROLEMEMBER(N'NHOM_SV', N'sv'), 0) = 0
    ALTER ROLE NHOM_SV ADD MEMBER sv;
GO

IF ISNULL(IS_ROLEMEMBER(N'db_securityadmin', N'pgv_admin'), 0) = 0
    ALTER ROLE db_securityadmin ADD MEMBER pgv_admin;
GO

GRANT ALTER ANY USER TO PGV;
GRANT ALTER ANY ROLE TO PGV;
GO

REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.KHOA FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.LOP FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.SINHVIEN FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.MONHOC FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.GIANGVIEN FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.LOPTINCHI FROM NHOM_SV, KHOA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON dbo.DANGKY FROM NHOM_SV, KHOA;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.KHOA TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.LOP TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.SINHVIEN TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.MONHOC TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GIANGVIEN TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.LOPTINCHI TO PGV;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DANGKY TO PGV;
GO

GRANT SELECT ON dbo.KHOA TO KHOA;
GRANT SELECT ON dbo.LOP TO KHOA;
GRANT SELECT ON dbo.SINHVIEN TO KHOA;
GRANT SELECT ON dbo.MONHOC TO KHOA;
GRANT SELECT ON dbo.GIANGVIEN TO KHOA;
GRANT SELECT ON dbo.LOPTINCHI TO KHOA;
GRANT SELECT ON dbo.DANGKY TO KHOA;
GO

GRANT SELECT ON dbo.KHOA TO NHOM_SV;
GRANT SELECT ON dbo.LOP TO NHOM_SV;
GRANT SELECT ON dbo.MONHOC TO NHOM_SV;
GRANT SELECT ON dbo.GIANGVIEN TO NHOM_SV;
GRANT SELECT ON dbo.LOPTINCHI TO NHOM_SV;
GO

IF DATABASE_PRINCIPAL_ID(N'PGV') IS NOT NULL
    GRANT EXECUTE ON SCHEMA::dbo TO PGV;
GO

IF DATABASE_PRINCIPAL_ID(N'KHOA') IS NOT NULL
BEGIN
    GRANT EXECUTE ON OBJECT::dbo.SP_ThongTinDangNhapSql TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachMonHoc TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenMonHoc TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopDropdown TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachGiangVienDropdown TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachNienKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_TimLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachSinhVienNhapDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_CapNhatDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDSLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDSSinhVienDangKy TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoBangDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiemSinhVienInfo TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoLopInfo TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoMonHocTheoLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoSinhVienTheoLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDiemTongKet TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoStudent TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoLop TO KHOA;
END;
GO

IF DATABASE_PRINCIPAL_ID(N'NHOM_SV') IS NOT NULL
BEGIN
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenKhoa TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_ThongTinSinhVienDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChiDaDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChiCoTheDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachMaLopTinChiDaDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DangKyLopTinChi TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_HuyDangKyLopTinChi TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiemSinhVienInfo TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiem TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoStudent TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_LoginSinhVien TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoLop TO NHOM_SV;
END;
GO

UPDATE dbo.SINHVIEN SET PASSWORD = '123456' WHERE PASSWORD IS NULL OR PASSWORD = '';
GO

PRINT N'SQL Server Login/User/Role permissions for QLDSV_HTC were configured.';
PRINT N'Logins: pgv_admin, khoa_cntt, khoa_vt, sv';
PRINT N'Roles: PGV, KHOA, NHOM_SV (application group SV)';
GO
