USE [QLDSV_HTC];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.TaiKhoan', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TaiKhoan (
        Login NVARCHAR(50) NOT NULL PRIMARY KEY,
        MatKhau NVARCHAR(50) NOT NULL,
        NhomQuyen NVARCHAR(20) NOT NULL,
        MAGV NCHAR(10) NULL,
        MAKHOA NCHAR(10) NULL,
        TrangThai NVARCHAR(20) NOT NULL CONSTRAINT DF_TaiKhoan_TrangThai DEFAULT N'Active',
        NgayTao DATETIME NOT NULL CONSTRAINT DF_TaiKhoan_NgayTao DEFAULT GETDATE()
    );
END;
GO

IF COL_LENGTH(N'dbo.TaiKhoan', N'MAGV') IS NULL
    ALTER TABLE dbo.TaiKhoan ADD MAGV NCHAR(10) NULL;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LoginSinhVien
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MASV, HO, TEN, MALOP
    FROM dbo.SINHVIEN
    WHERE MASV = @MASV AND DANGHIHOC = 0;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LoginTaiKhoan
    @Login NVARCHAR(50),
    @MatKhau NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM dbo.TaiKhoan
    WHERE Login = @Login
      AND MatKhau = @MatKhau
      AND TrangThai = N'Active';
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachKhoa
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAKHOA, TENKHOA
    FROM dbo.KHOA
    ORDER BY MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LayTenKhoa
    @MAKHOA NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TENKHOA
    FROM dbo.KHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LayKhoaTheoLop
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAKHOA
    FROM dbo.LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachMonHoc
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAMH, TENMH, SOTIET_LT, SOTIET_TH
    FROM dbo.MONHOC
    ORDER BY TENMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LayTenMonHoc
    @MAMH NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TENMH
    FROM dbo.MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThemMonHoc
    @MAMH NCHAR(10),
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.MONHOC WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Mã môn học đã tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.MONHOC WHERE TENMH = @TENMH)
    BEGIN
        THROW 50000, N'Tên môn học đã tồn tại.', 1;
    END;

    IF @SOTIET_LT < 0 OR @SOTIET_TH < 0
    BEGIN
        THROW 50000, N'Số tiết lý thuyết và thực hành không được âm.', 1;
    END;

    INSERT INTO dbo.MONHOC (MAMH, TENMH, SOTIET_LT, SOTIET_TH)
    VALUES (@MAMH, @TENMH, @SOTIET_LT, @SOTIET_TH);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatMonHoc
    @TENMH NVARCHAR(50),
    @SOTIET_LT INT,
    @SOTIET_TH INT,
    @MAMH NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.MONHOC WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Môn học không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.MONHOC WHERE TENMH = @TENMH AND MAMH <> @MAMH)
    BEGIN
        THROW 50000, N'Tên môn học đã được sử dụng cho môn học khác.', 1;
    END;

    IF @SOTIET_LT < 0 OR @SOTIET_TH < 0
    BEGIN
        THROW 50000, N'Số tiết lý thuyết và thực hành không được âm.', 1;
    END;

    UPDATE dbo.MONHOC
    SET TENMH = @TENMH,
        SOTIET_LT = @SOTIET_LT,
        SOTIET_TH = @SOTIET_TH
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaMonHoc
    @MAMH NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.MONHOC WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Môn học không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Môn học đã được dùng cho lớp tín chỉ, không thể xóa.', 1;
    END;

    DELETE FROM dbo.MONHOC
    WHERE MAMH = @MAMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachLop
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT L.*, K.TENKHOA
    FROM dbo.LOP AS L
    JOIN dbo.KHOA AS K ON L.MAKHOA = K.MAKHOA
    WHERE @MAKHOA IS NULL OR L.MAKHOA = @MAKHOA
    ORDER BY L.MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachLopDropdown
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MALOP, TENLOP
    FROM dbo.LOP
    WHERE @MAKHOA IS NULL OR MAKHOA = @MAKHOA
    ORDER BY MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThemLop
    @MALOP NCHAR(10),
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Mã lớp đã tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOP WHERE TENLOP = @TENLOP)
    BEGIN
        THROW 50000, N'Tên lớp đã tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    INSERT INTO dbo.LOP (MALOP, TENLOP, KHOAHOC, MAKHOA)
    VALUES (@MALOP, @TENLOP, @KHOAHOC, @MAKHOA);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatLop
    @TENLOP NVARCHAR(50),
    @KHOAHOC NCHAR(9),
    @MAKHOA NCHAR(10),
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Lớp không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOP WHERE TENLOP = @TENLOP AND MALOP <> @MALOP)
    BEGIN
        THROW 50000, N'Tên lớp đã được sử dụng cho lớp khác.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    UPDATE dbo.LOP
    SET TENLOP = @TENLOP,
        KHOAHOC = @KHOAHOC,
        MAKHOA = @MAKHOA
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaLop
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Lớp không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Lớp đã có sinh viên, không thể xóa.', 1;
    END;

    DELETE FROM dbo.LOP
    WHERE MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachGiangVien
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT G.*, K.TENKHOA
    FROM dbo.GIANGVIEN AS G
    JOIN dbo.KHOA AS K ON G.MAKHOA = K.MAKHOA
    WHERE @MAKHOA IS NULL OR G.MAKHOA = @MAKHOA
    ORDER BY G.TEN;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachGiangVienDropdown
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAGV, HO + N' ' + TEN AS HOTENGV
    FROM dbo.GIANGVIEN
    WHERE @MAKHOA IS NULL OR MAKHOA = @MAKHOA
    ORDER BY TEN;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThemGiangVien
    @MAGV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20) = NULL,
    @HOCHAM NVARCHAR(20) = NULL,
    @CHUYENMON NVARCHAR(50) = NULL,
    @MAKHOA NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Mã giảng viên đã tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    INSERT INTO dbo.GIANGVIEN (MAGV, HO, TEN, HOCVI, HOCHAM, CHUYENMON, MAKHOA)
    VALUES (@MAGV, @HO, @TEN, @HOCVI, @HOCHAM, @CHUYENMON, @MAKHOA);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatGiangVien
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @HOCVI NVARCHAR(20) = NULL,
    @HOCHAM NVARCHAR(20) = NULL,
    @CHUYENMON NVARCHAR(50) = NULL,
    @MAKHOA NCHAR(10),
    @MAGV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    UPDATE dbo.GIANGVIEN
    SET HO = @HO,
        TEN = @TEN,
        HOCVI = @HOCVI,
        HOCHAM = @HOCHAM,
        CHUYENMON = @CHUYENMON,
        MAKHOA = @MAKHOA
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaGiangVien
    @MAGV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên đã được phân công lớp tín chỉ, không thể xóa.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.TaiKhoan WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên đang có tài khoản đăng nhập, không thể xóa.', 1;
    END;

    DELETE FROM dbo.GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachSinhVienTheoLop
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM dbo.SINHVIEN
    WHERE MALOP = @MALOP
    ORDER BY TEN, HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThemSinhVien
    @MASV NCHAR(10),
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT,
    @PASSWORD NVARCHAR(40) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MASV = @MASV)
    BEGIN
        THROW 50000, N'Mã sinh viên đã tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Lớp học không tồn tại.', 1;
    END;

    INSERT INTO dbo.SINHVIEN (MASV, HO, TEN, MALOP, PHAI, NGAYSINH, DIACHI, DANGHIHOC, PASSWORD)
    VALUES (@MASV, @HO, @TEN, @MALOP, @PHAI, @NGAYSINH, @DIACHI, @DANGHIHOC, @PASSWORD);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatSinhVien
    @HO NVARCHAR(50),
    @TEN NVARCHAR(10),
    @MALOP NCHAR(10),
    @PHAI BIT,
    @NGAYSINH DATE = NULL,
    @DIACHI NVARCHAR(100) = NULL,
    @DANGHIHOC BIT,
    @PASSWORD NVARCHAR(40) = NULL,
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MASV = @MASV)
    BEGIN
        THROW 50000, N'Sinh viên không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE MALOP = @MALOP)
    BEGIN
        THROW 50000, N'Lớp học không tồn tại.', 1;
    END;

    UPDATE dbo.SINHVIEN
    SET HO = @HO,
        TEN = @TEN,
        MALOP = @MALOP,
        PHAI = @PHAI,
        NGAYSINH = @NGAYSINH,
        DIACHI = @DIACHI,
        DANGHIHOC = @DANGHIHOC,
        PASSWORD = @PASSWORD
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaSinhVien
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MASV = @MASV)
    BEGIN
        THROW 50000, N'Sinh viên không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.DANGKY WHERE MASV = @MASV)
    BEGIN
        THROW 50000, N'Sinh viên đã đăng ký lớp tín chỉ, không thể xóa.', 1;
    END;

    DELETE FROM dbo.SINHVIEN
    WHERE MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachLopTinChi
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT LTC.*, MH.TENMH, GV.HO + N' ' + GV.TEN AS HOTENGV,
           (SELECT COUNT(*)
            FROM dbo.DANGKY AS DK
            WHERE DK.MALTC = LTC.MALTC
              AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)) AS SOSVDK
    FROM dbo.LOPTINCHI AS LTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    JOIN dbo.GIANGVIEN AS GV ON LTC.MAGV = GV.MAGV
    WHERE @MAKHOA IS NULL OR LTC.MAKHOA = @MAKHOA
    ORDER BY LTC.NIENKHOA DESC, LTC.HOCKY, MH.TENMH, LTC.NHOM;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThemLopTinChi
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @MAKHOA NCHAR(10),
    @SOSVTOITHIEU INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.MONHOC WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Môn học không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MAMH AND NHOM = @NHOM)
    BEGIN
        THROW 50000, N'Lớp tín chỉ này đã tồn tại.', 1;
    END;

    IF @SOSVTOITHIEU <= 0
    BEGIN
        THROW 50000, N'Số sinh viên tối thiểu phải lớn hơn 0.', 1;
    END;

    INSERT INTO dbo.LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, MAKHOA, SOSVTOITHIEU, HUYLOP)
    VALUES (@NIENKHOA, @HOCKY, @MAMH, @NHOM, @MAGV, @MAKHOA, @SOSVTOITHIEU, 0);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatLopTinChi
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAGV NCHAR(10),
    @SOSVTOITHIEU INT,
    @MALTC INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MALTC = @MALTC)
    BEGIN
        THROW 50000, N'Lớp tín chỉ không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.MONHOC WHERE MAMH = @MAMH)
    BEGIN
        THROW 50000, N'Môn học không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MAMH AND NHOM = @NHOM AND MALTC <> @MALTC)
    BEGIN
        THROW 50000, N'Lớp tín chỉ khác có cùng thông tin niên khóa, học kỳ, môn học, nhóm đã tồn tại.', 1;
    END;

    IF @SOSVTOITHIEU <= 0
    BEGIN
        THROW 50000, N'Số sinh viên tối thiểu phải lớn hơn 0.', 1;
    END;

    UPDATE dbo.LOPTINCHI
    SET NIENKHOA = @NIENKHOA,
        HOCKY = @HOCKY,
        MAMH = @MAMH,
        NHOM = @NHOM,
        MAGV = @MAGV,
        SOSVTOITHIEU = @SOSVTOITHIEU
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaLopTinChi
    @MALTC INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MALTC = @MALTC)
    BEGIN
        THROW 50000, N'Lớp tín chỉ không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.DANGKY WHERE MALTC = @MALTC)
    BEGIN
        THROW 50000, N'Lớp tín chỉ đã có sinh viên đăng ký, không thể xóa.', 1;
    END;

    DELETE FROM dbo.LOPTINCHI
    WHERE MALTC = @MALTC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachNienKhoa
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DISTINCT NIENKHOA
    FROM dbo.LOPTINCHI
    WHERE @MAKHOA IS NULL OR MAKHOA = @MAKHOA
    ORDER BY NIENKHOA DESC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_TimLopTinChi
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAMH NCHAR(10),
    @NHOM INT,
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MALTC
    FROM dbo.LOPTINCHI
    WHERE NIENKHOA = @NIENKHOA
      AND HOCKY = @HOCKY
      AND MAMH = @MAMH
      AND NHOM = @NHOM
      AND (@MAKHOA IS NULL OR MAKHOA = @MAKHOA);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachSinhVienNhapDiem
    @MALTC INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DK.MASV, SV.HO + N' ' + SV.TEN AS HOTENSV,
           DK.DIEM_CC, DK.DIEM_GK, DK.DIEM_CK
    FROM dbo.DANGKY AS DK
    JOIN dbo.SINHVIEN AS SV ON DK.MASV = SV.MASV
    WHERE DK.MALTC = @MALTC
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    ORDER BY SV.TEN, SV.HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CapNhatDiem
    @DIEM_CC INT = NULL,
    @DIEM_GK FLOAT = NULL,
    @DIEM_CK FLOAT = NULL,
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.DANGKY WHERE MALTC = @MALTC AND MASV = @MASV)
    BEGIN
        THROW 50000, N'Thông tin đăng ký lớp tín chỉ không tồn tại.', 1;
    END;

    IF (@DIEM_CC IS NOT NULL AND (@DIEM_CC < 0 OR @DIEM_CC > 10))
       OR (@DIEM_GK IS NOT NULL AND (@DIEM_GK < 0.0 OR @DIEM_GK > 10.0))
       OR (@DIEM_CK IS NOT NULL AND (@DIEM_CK < 0.0 OR @DIEM_CK > 10.0))
    BEGIN
        THROW 50000, N'Điểm nhập vào phải nằm trong khoảng từ 0 đến 10.', 1;
    END;

    UPDATE dbo.DANGKY
    SET DIEM_CC = @DIEM_CC,
        DIEM_GK = @DIEM_GK,
        DIEM_CK = @DIEM_CK
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_ThongTinSinhVienDangKy
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT SV.MASV, SV.HO, SV.TEN, SV.MALOP, L.TENLOP
    FROM dbo.SINHVIEN AS SV
    JOIN dbo.LOP AS L ON SV.MALOP = L.MALOP
    WHERE SV.MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachLopTinChiDaDangKy
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DK.MALTC, MH.MAMH, MH.TENMH, LTC.NHOM, LTC.NIENKHOA, LTC.HOCKY,
           GV.HO + N' ' + GV.TEN AS HOTENGV, DK.HUYDANGKY
    FROM dbo.DANGKY AS DK
    JOIN dbo.LOPTINCHI AS LTC ON DK.MALTC = LTC.MALTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    JOIN dbo.GIANGVIEN AS GV ON LTC.MAGV = GV.MAGV
    WHERE DK.MASV = @MASV
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    ORDER BY LTC.NIENKHOA DESC, LTC.HOCKY, MH.TENMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachLopTinChiCoTheDangKy
    @NIENKHOA NCHAR(9),
    @HOCKY INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT LTC.MALTC, MH.MAMH, MH.TENMH, LTC.NHOM,
           GV.HO + N' ' + GV.TEN AS HOTENGV,
           (SELECT COUNT(*)
            FROM dbo.DANGKY AS DK
            WHERE DK.MALTC = LTC.MALTC
              AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)) AS SOSVDK
    FROM dbo.LOPTINCHI AS LTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    JOIN dbo.GIANGVIEN AS GV ON LTC.MAGV = GV.MAGV
    WHERE LTC.NIENKHOA = @NIENKHOA
      AND LTC.HOCKY = @HOCKY
      AND LTC.HUYLOP = 0
    ORDER BY MH.TENMH, LTC.NHOM;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachMaLopTinChiDaDangKy
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DK.MALTC
    FROM dbo.DANGKY AS DK
    WHERE DK.MASV = @MASV
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DangKyLopTinChi
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MASV = @MASV)
    BEGIN
        THROW 50000, N'Sinh viên không tồn tại.', 1;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MALTC = @MALTC)
    BEGIN
        THROW 50000, N'Lớp tín chỉ không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MALTC = @MALTC AND HUYLOP = 1)
    BEGIN
        THROW 50000, N'Lớp tín chỉ đã bị hủy, không thể đăng ký.', 1;
    END;

    IF EXISTS (
        SELECT 1
        FROM dbo.DANGKY WITH (UPDLOCK, HOLDLOCK)
        WHERE MALTC = @MALTC AND MASV = @MASV
    )
    BEGIN
        UPDATE dbo.DANGKY
        SET HUYDANGKY = 0
        WHERE MALTC = @MALTC AND MASV = @MASV;
    END
    ELSE
    BEGIN
        INSERT INTO dbo.DANGKY (MALTC, MASV, HUYDANGKY)
        VALUES (@MALTC, @MASV, 0);
    END;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_HuyDangKyLopTinChi
    @MALTC INT,
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.DANGKY WHERE MALTC = @MALTC AND MASV = @MASV AND (HUYDANGKY = 0 OR HUYDANGKY IS NULL))
    BEGIN
        THROW 50000, N'Không tìm thấy thông tin đăng ký lớp tín chỉ hợp lệ để hủy.', 1;
    END;

    UPDATE dbo.DANGKY
    SET HUYDANGKY = 1
    WHERE MALTC = @MALTC AND MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_DanhSachTaiKhoanGiangVien
AS
BEGIN
    SET NOCOUNT ON;

    SELECT G.MAGV, G.HO + N' ' + G.TEN AS HOTEN,
           T.Login, T.MatKhau, T.NhomQuyen, T.MAKHOA
    FROM dbo.GIANGVIEN AS G
    LEFT JOIN dbo.TaiKhoan AS T ON G.MAGV = T.MAGV
    ORDER BY G.TEN, G.HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LayNhomQuyenTheoGiangVien
    @MAGV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT NhomQuyen
    FROM dbo.TaiKhoan
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_LuuTaiKhoanGiangVien
    @MAGV NCHAR(10),
    @Login NVARCHAR(50),
    @MatKhau NVARCHAR(50),
    @NhomQuyen NVARCHAR(20),
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.TaiKhoan WHERE Login = @Login AND MAGV <> @MAGV)
    BEGIN
        THROW 50000, N'Tên đăng nhập đã tồn tại cho một giảng viên khác.', 1;
    END;

    IF ISNULL(IS_MEMBER(N'KHOA'), 0) = 1 AND @NhomQuyen = N'PGV'
    BEGIN
        THROW 50001, N'Khoa khong duoc cap tai khoan nhom PGV.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.TaiKhoan WHERE MAGV = @MAGV)
    BEGIN
        UPDATE dbo.TaiKhoan
        SET Login = @Login,
            MatKhau = @MatKhau,
            NhomQuyen = @NhomQuyen,
            MAKHOA = @MAKHOA,
            TrangThai = N'Active'
        WHERE MAGV = @MAGV;
    END
    ELSE
    BEGIN
        INSERT INTO dbo.TaiKhoan (Login, MatKhau, NhomQuyen, MAGV, MAKHOA, TrangThai, NgayTao)
        VALUES (@Login, @MatKhau, @NhomQuyen, @MAGV, @MAKHOA, N'Active', GETDATE());
    END;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_XoaTaiKhoanTheoGiangVien
    @MAGV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.TaiKhoan WHERE MAGV = @MAGV)
    BEGIN
        THROW 50000, N'Giảng viên này không có tài khoản đăng nhập nào.', 1;
    END;

    IF ISNULL(IS_MEMBER(N'KHOA'), 0) = 1
       AND EXISTS (SELECT 1 FROM dbo.TaiKhoan WHERE MAGV = @MAGV AND NhomQuyen = N'PGV')
    BEGIN
        THROW 50002, N'Khoa khong co quyen xoa tai khoan nhom PGV.', 1;
    END;

    DELETE FROM dbo.TaiKhoan
    WHERE MAGV = @MAGV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoDSLopTinChi
    @NIENKHOA NCHAR(9),
    @HOCKY INT,
    @MAKHOA NCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MH.TENMH, LTC.NHOM, GV.HO + N' ' + GV.TEN AS HOTENGV,
           LTC.SOSVTOITHIEU,
           (SELECT COUNT(*)
            FROM dbo.DANGKY AS DK
            WHERE DK.MALTC = LTC.MALTC
              AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)) AS SOSVDK
    FROM dbo.LOPTINCHI AS LTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    JOIN dbo.GIANGVIEN AS GV ON LTC.MAGV = GV.MAGV
    WHERE LTC.NIENKHOA = @NIENKHOA
      AND LTC.HOCKY = @HOCKY
      AND LTC.HUYLOP = 0
      AND (@MAKHOA IS NULL OR LTC.MAKHOA = @MAKHOA)
    ORDER BY MH.TENMH, LTC.NHOM;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoDSSinhVienDangKy
    @MALTC INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT SV.MASV, SV.HO, SV.TEN, SV.PHAI, SV.MALOP
    FROM dbo.DANGKY AS DK
    JOIN dbo.SINHVIEN AS SV ON DK.MASV = SV.MASV
    WHERE DK.MALTC = @MALTC
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    ORDER BY SV.TEN, SV.HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoBangDiem
    @MALTC INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT SV.MASV, SV.HO, SV.TEN, DK.DIEM_CC, DK.DIEM_GK, DK.DIEM_CK
    FROM dbo.DANGKY AS DK
    JOIN dbo.SINHVIEN AS SV ON DK.MASV = SV.MASV
    WHERE DK.MALTC = @MALTC
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    ORDER BY SV.TEN, SV.HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoPhieuDiemSinhVienInfo
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT SV.MASV, SV.HO, SV.TEN, SV.MALOP, L.TENLOP, K.TENKHOA
    FROM dbo.SINHVIEN AS SV
    JOIN dbo.LOP AS L ON SV.MALOP = L.MALOP
    JOIN dbo.KHOA AS K ON L.MAKHOA = K.MAKHOA
    WHERE SV.MASV = @MASV;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoPhieuDiem
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MH.TENMH,
           MAX(ISNULL(DK.DIEM_CC, 0) * 0.1
             + ISNULL(DK.DIEM_GK, 0) * 0.3
             + ISNULL(DK.DIEM_CK, 0) * 0.6) AS DIEM
    FROM dbo.DANGKY AS DK
    JOIN dbo.LOPTINCHI AS LTC ON DK.MALTC = LTC.MALTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    WHERE DK.MASV = @MASV
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    GROUP BY MH.TENMH
    ORDER BY MH.TENMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoLopInfo
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT L.MALOP, L.TENLOP, L.KHOAHOC, K.TENKHOA
    FROM dbo.LOP AS L
    JOIN dbo.KHOA AS K ON L.MAKHOA = K.MAKHOA
    WHERE L.MALOP = @MALOP;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoMonHocTheoLop
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DISTINCT MH.MAMH, MH.TENMH
    FROM dbo.DANGKY AS DK
    JOIN dbo.LOPTINCHI AS LTC ON DK.MALTC = LTC.MALTC
    JOIN dbo.MONHOC AS MH ON LTC.MAMH = MH.MAMH
    JOIN dbo.SINHVIEN AS SV ON DK.MASV = SV.MASV
    WHERE SV.MALOP = @MALOP
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    ORDER BY MH.TENMH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoSinhVienTheoLop
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MASV, HO + N' ' + TEN AS HOTENSV
    FROM dbo.SINHVIEN
    WHERE MALOP = @MALOP
    ORDER BY TEN, HO;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_BaoCaoDiemTongKet
    @MALOP NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT DK.MASV, LTC.MAMH,
           MAX(ISNULL(DK.DIEM_CC, 0) * 0.1
             + ISNULL(DK.DIEM_GK, 0) * 0.3
             + ISNULL(DK.DIEM_CK, 0) * 0.6) AS DIEM
    FROM dbo.DANGKY AS DK
    JOIN dbo.LOPTINCHI AS LTC ON DK.MALTC = LTC.MALTC
    JOIN dbo.SINHVIEN AS SV ON DK.MASV = SV.MASV
    WHERE SV.MALOP = @MALOP
      AND (DK.HUYDANGKY = 0 OR DK.HUYDANGKY IS NULL)
    GROUP BY DK.MASV, LTC.MAMH;
END;
GO

-- =============================================
-- SP THÊM KHOA
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_ThemKhoa
    @MAKHOA NCHAR(10),
    @TENKHOA NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Mã khoa đã tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.KHOA WHERE TENKHOA = @TENKHOA)
    BEGIN
        THROW 50000, N'Tên khoa đã tồn tại.', 1;
    END;

    INSERT INTO dbo.KHOA (MAKHOA, TENKHOA)
    VALUES (@MAKHOA, @TENKHOA);
END;
GO

-- =============================================
-- SP CẬP NHẬT KHOA
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_CapNhatKhoa
    @TENKHOA NVARCHAR(50),
    @MAKHOA NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    IF EXISTS (SELECT 1 FROM dbo.KHOA WHERE TENKHOA = @TENKHOA AND MAKHOA <> @MAKHOA)
    BEGIN
        THROW 50000, N'Tên khoa đã được sử dụng cho khoa khác.', 1;
    END;

    UPDATE dbo.KHOA
    SET TENKHOA = @TENKHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

-- =============================================
-- SP XÓA KHOA (Có kiểm tra ràng buộc ngoại)
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_XoaKhoa
    @MAKHOA NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.KHOA WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa không tồn tại.', 1;
    END;

    -- Kiểm tra bảng LOP
    IF EXISTS (SELECT 1 FROM dbo.LOP WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa đã có lớp học, không thể xóa.', 1;
    END;

    -- Kiểm tra bảng GIANGVIEN
    IF EXISTS (SELECT 1 FROM dbo.GIANGVIEN WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa đã có giảng viên, không thể xóa.', 1;
    END;

    -- Kiểm tra bảng LOPTINCHI
    IF EXISTS (SELECT 1 FROM dbo.LOPTINCHI WHERE MAKHOA = @MAKHOA)
    BEGIN
        THROW 50000, N'Khoa đã có lớp tín chỉ, không thể xóa.', 1;
    END;

    DELETE FROM dbo.KHOA
    WHERE MAKHOA = @MAKHOA;
END;
GO

-- =============================================
-- SP LẤY KHOA THEO GIẢNG VIÊN
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_LayKhoaTheoGiangVien
    @MAGV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MAKHOA
    FROM dbo.GIANGVIEN
    WHERE MAGV = @MAGV;
END;
GO

-- =============================================
-- SP LẤY KHOA THEO SINH VIÊN
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_LayKhoaTheoStudent
    @MASV NCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT L.MAKHOA
    FROM dbo.SINHVIEN AS SV
    JOIN dbo.LOP AS L ON SV.MALOP = L.MALOP
    WHERE SV.MASV = @MASV;
END;
GO

-- =============================================
-- SP LẤY DANH SÁCH GIẢNG VIÊN CÓ KHOA THỰC TẾ
-- =============================================
CREATE OR ALTER PROCEDURE dbo.SP_DanhSachTaiKhoanGiangVienCoKhoa
AS
BEGIN
    SET NOCOUNT ON;

    SELECT G.MAGV, G.HO + N' ' + G.TEN AS HOTEN,
           T.Login, T.MatKhau, T.NhomQuyen, G.MAKHOA
    FROM dbo.GIANGVIEN AS G
    LEFT JOIN dbo.TaiKhoan AS T ON G.MAGV = T.MAGV
    ORDER BY G.TEN, G.HO;
END;
GO

IF DATABASE_PRINCIPAL_ID(N'PGV') IS NOT NULL
    GRANT EXECUTE ON SCHEMA::dbo TO PGV;
GO

IF DATABASE_PRINCIPAL_ID(N'KHOA') IS NOT NULL
BEGIN
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachMonHoc TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenMonHoc TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopDropdown TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachGiangVienDropdown TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachNienKhoa TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_TimLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachSinhVienNhapDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_CapNhatDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachTaiKhoanGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayNhomQuyenTheoGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LuuTaiKhoanGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_XoaTaiKhoanTheoGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDSLopTinChi TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDSSinhVienDangKy TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoBangDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiemSinhVienInfo TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiem TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoLopInfo TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoMonHocTheoLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoSinhVienTheoLop TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoDiemTongKet TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoGiangVien TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoStudent TO KHOA;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachTaiKhoanGiangVienCoKhoa TO KHOA;
END;
GO

IF DATABASE_PRINCIPAL_ID(N'NHOM_SV') IS NOT NULL
BEGIN
    GRANT EXECUTE ON OBJECT::dbo.SP_LayTenKhoa TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_ThongTinSinhVienDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChiDaDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachLopTinChiCoTheDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DanhSachMaLopTinChiDaDangKy TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_DangKyLopTinChi TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_HuyDangKyLopTinChi TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiemSinhVienInfo TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_BaoCaoPhieuDiem TO NHOM_SV;
    GRANT EXECUTE ON OBJECT::dbo.SP_LayKhoaTheoStudent TO NHOM_SV;
END;
GO

PRINT N'Stored procedures for QLDSV_HTC were created successfully.';
GO
